### ISSUE TITLE
how to change url's?

### ISSUE THREAD

**Issue by omega3** [navn-r/newtab#1]
Tell me please, how do you change default url's? I can't see any settings nor script.js in mozilla folders.

**Comment by navn-r** [comment]
Hey,

Honestly this project was really for my own use, didn't think anyone else would use it. In order to modify the extension for your own purposes, feel free to fork the repository and modify script.js and update the bookmarks object where you can change the href and the other properties.

Thanks.

**Comment by navn-r** [comment]
Closing this for now, contributions to add the ability to change the url are still welcomed.

✌️💖
